# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  amd64-ubuntu:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    working_directory: ~/project

  arm64-ubuntu:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    working_directory: ~/project

  i386-ubuntu:
    docker:
      - image: i386/ubuntu:latest
    resource_class: medium
    working_directory: ~/project

  arm64-macos:
    macos:
      xcode: "14.0.0"
    resource_class: medium
    working_directory: ~/project
    environment:
      HOMEBREW_NO_AUTO_UPDATE: true
  amd64-macos:
    macos:
      xcode: "13.3.0"
    resource_class: macos.x86.medium.gen2
    working_directory: ~/project
    environment:
      HOMEBREW_NO_AUTO_UPDATE: true

jobs:
  amd64-ubuntu:
    executor: amd64-ubuntu
    steps:
      - checkout
      - run:
          name: "Install Maven"
          command: "sudo apt-get update && sudo apt-get install -y maven"
      - run:
          name: "Check Arch"
          command: "uname -sm"
      - run:
          name: "Run Package"
          command: "mvn clean package"

  arm64-ubuntu:
    executor: arm64-ubuntu
    steps:
      - checkout
      - run:
          name: "Install Maven"
          command: "sudo apt-get update && sudo apt-get install -y maven"
      - run:
          name: "Check Arch"
          command: "uname -sm"
      - run:
          name: "Run Package"
          command: "mvn clean package"

  i386-ubuntu:
    executor: i386-ubuntu
    steps:
      - checkout
      - run:
          name: "Install Maven"
          command: "apt-get update && apt-get install -y maven"
      - run:
          name: "Check Arch"
          command: "uname -sm"
      - run:
          name: "Run Package"
          command: "mvn clean package"

  arm64-macos:
    executor: arm64-macos
    steps:
      - checkout
      - run:
          name: "Install Maven"
          command: "brew install maven"
      - run:
          name: "Check Arch"
          command: "uname -sm"
      - run:
          name: "Run Package"
          command: "mvn clean package"
  amd64-macos:
    executor: amd64-macos
    steps:
      - checkout
      - run:
          name: "Install Maven"
          command: "brew install maven"
      - run:
          name: "Check Arch"
          command: "uname -sm"
      - run:
          name: "Run Package"
          command: "mvn clean package"

workflows:
  all-tests:
    jobs:
      - amd64-ubuntu
      - arm64-ubuntu
      - arm64-macos
      - amd64-macos
